from pprint import pprint

dct_value_inverting = {
    '💸AUD/CAD💸': '47',
    '💸AUD/CHF💸': '48',
    '💸AUD/GBP💸': '1489',
    '💸AUD/JPY💸': '49',
    '💸AUD/USD💸': '5',
    '💸CAD/CHF💸': '14',
    '💸CAD/JPY💸': '51',
    '💸CHF/JPY💸': '13',
    '💸EUR/AUD💸': '15',
    '💸EUR/CAD💸': '16',
    '💸EUR/CHF💸': '10',
    '💸EUR/GBP💸': '6',
    '💸EUR/JPY💸': '9',
    '💸EUR/USD💸': '1',
    '💸GBP/AUD💸': '53',
    '💸GBP/CAD💸': '54',
    '💸GBP/JPY💸': '11',
    '💸GBP/USD💸': '2',
    '💸USD/CAD💸': '7',
    '💸USD/CHF💸': '4',
    '💸USD/JPY💸': '3'}

reverse_dct_value_inverting = {
    '1': '💸EUR/USD💸',
    '10': '💸EUR/CHF💸',
    '11': '💸GBP/JPY💸',
    '13': '💸CHF/JPY💸',
    '14': '💸CAD/CHF💸',
    '1489': '💸AUD/GBP💸',
    '15': '💸EUR/AUD💸',
    '16': '💸EUR/CAD💸',
    '2': '💸GBP/USD💸',
    '3': '💸USD/JPY💸',
    '4': '💸USD/CHF💸',
    '47': '💸AUD/CAD💸',
    '48': '💸AUD/CHF💸',
    '49': '💸AUD/JPY💸',
    '5': '💸AUD/USD💸',
    '51': '💸CAD/JPY💸',
    '53': '💸GBP/AUD💸',
    '54': '💸GBP/CAD💸',
    '6': '💸EUR/GBP💸',
    '7': '💸USD/CAD💸',
    '9': '💸EUR/JPY💸'}
